# Sample Home-Assistant automation code that can be used with the ESP8266 module
- alias: Motion 1 On
  trigger:
    platform: mqtt
    topic: sensor/motion1
    payload: 'controlOn'
  action:
   service: light.turn_on
   entity_id: 
    - light.living_room

- alias: Motion 1 Off
  trigger:
    platform: mqtt
    topic: sensor/motion1
    payload: 'controlOff'
  action:
   service: light.turn_off
   entity_id: 
    - light.living_room

- alias: Button 1 Toggle
  trigger:
    platform: mqtt
    topic: sensor/button1
    payload: 'controlOn'
  action:
   service: light.toggle
   entity_id: 
    - light.living_room
